### ISSUE TITLE
Replace shen-clisp and shen-sbcl with this combined repo?

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-cl#1]
@tizoc So I made this repo today with CL code that uses reader conditionals (if that's what they're called in CL) to distinguish with CL implementation is being built. This allows the same code to be used for CLisp, SBCL and potentially more.

```lisp
#+CLISP (EXT:SAVEINITMEM
  (FORMAT NIL "~A~A" *NATIVE-PATH* "shen.mem")
  :INIT-FUNCTION 'shen.byteloop)

#+SBCL (SAVE-LISP-AND-DIE
  (FORMAT NIL "~A~A" *NATIVE-PATH* #+WIN32 "shen.exe" #-WIN32 "shen")
  :EXECUTABLE T
  :SAVE-RUNTIME-OPTIONS T
  :TOPLEVEL 'SHEN-TOPLEVEL)
```

After working on both CL ports in parallel for a while, (two text editors side by side), I noticed how similar they were and keeping them in sync was getting annoying.

What do you think about just having a combined repo?

**Comment by tizoc** [comment]
Big +1 from me, I was considering proposing doing this being that most of the code is shared.

**Comment by tizoc** [comment]
@rkoeninger I added you to the Shen-Language organization, does github let you transfer the repo now? (I'm not sure if I set up the permissions right)

If not, let me know. It may take a while, I'm having problems with my ISP and the only internet connection I have is through my mobile, and it doesn't work very well.

**Comment by rkoeninger** [comment]
@tizoc "You don’t have the permission to create repositories on Shen-Language"

**Comment by tizoc** [comment]
Ok, I added you to a "group", I think thats what was missing (Github changed the way organizations work, I'm still not sure I understand the new system).

**Comment by rkoeninger** [comment]
Got it transferred, thanks.
