### ISSUE TITLE
Changes required for Shen 21.0

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-cl#10]
List of changes:

- add `(import-kl "dict")` after the "sys" load in `boot.lsp`. Should there be an `if` so that it only happens for versions >= 21?
- rename `exit` to something else? (it is not part of the kernel anymore)
- rename `read-char-code` to `shen.read-char-code`.

I think thats all is needed, haven't found anything else so far.

**Comment by rkoeninger** [comment]
These were handled in #11.
