### ISSUE TITLE
Using the (lisp.sin...) capability fails

### ISSUE THREAD

**Issue by bluejay77** [Shen-Language/shen-cl#13]
I had a problem calling LISP from Shen in the shen-cl GitHub OS Shen,
with the (lisp.sin...) capability.

Examples below.

==================================================

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 21
running under Common Lisp, implementation: Clozure CL
port 2.2 ported by Mark Tarver


(0-) (lisp.sin 1.5)
0.9974949866040544

(1-) (lisp.print "Hellou")

"Hellou" "Hellou"

(2-) (lisp.format () "Hellou")
Too few arguments in call to #<Compiled-function FORMAT #x30000009CA2F>:
1 argument provided, at least 2 required. 

(3-) (lisp.* 3 3 3 3 3 3)
Too few arguments in call to #<Compiled-function shen.multiply #x30000118AAAF>:
1 argument provided, at least 2 required. 

(4-) (lisp.list a b c d e f)
(a) is not of type (OR SYMBOL FUNCTION), and can't be FUNCALLed or APPLYed

(5-) (QUIT)

Process inferior-shen finished
```

==================================================

This was said to work inside function definitions (because the
`protect` wrapper is stripped), only in the REPL it fails.

Outside of function definitions, the result is a symbol, and because
of that it gets compiled to a call to `shen.apply` and thats where it
fails.

Inside function definitions: (lisp.some-func 1 2 3 4) -> (SOME-FUNC 1
2 3 4)

In the REPL: (lisp.some-func 1 2 3 4) -> ((protect SOME-FUNC) 1 2 3 4)
-> (shen.apply (QUOTE SOME-FUNC) (LIST 1 2 3 4))

yours, Dr A. J. Y.
Finland, the EU

**Comment by rkoeninger** [comment]
I did a quick investigation in the sources and see in [core.shen](https://github.com/Shen-Language/shen-sources/blob/master/sources/core.shen) that the `protect` wrapper is removed in the following stack trace:

at strip-protect, [core.shen line 170](https://github.com/Shen-Language/shen-sources/blob/master/sources/core.shen#L170)
at compile_to_lambda+, [core.shen line 130](https://github.com/Shen-Language/shen-sources/blob/master/sources/core.shen#L130)
at compile_to_machine_code, [core.shen line 115](https://github.com/Shen-Language/shen-sources/blob/master/sources/core.shen#L115)
at \<define\>, [core.shen line 40, 41](https://github.com/Shen-Language/shen-sources/blob/master/sources/core.shen#L40-L41)

`strip-protect` is not called in any other code paths. We could start calling it in `typecheck-and-evaluate`, [toplevel.shen line 200](https://github.com/Shen-Language/shen-sources/blob/master/sources/toplevel.shen#L200).

We could also have this problem with root level expressions in `*.shen` files, as those expressions are not in `define`s, just like the repl. A good solution would handle of these situtions (expr in or out of a `define`, in a file or in the repl).

**Comment by tizoc** [comment]
@rkoeninger I haven't thought much about this one, but I was never too convinced by how native calls are handled by a macro instead of the Kl->Lisp compiler.

Do you think there is a better solution than having the compiler handle it and get rid of the macro?

**Comment by tizoc** [comment]
> strip-protect is not called in any other code paths. We could start calling it in typecheck-and-evaluate, toplevel.shen line 200.
>
> We could also have this problem with root level expressions in *.shen files, as those expressions are not in defines, just like the repl. A good solution would handle of these situtions (expr in or out of a define, in a file or in the repl).

This makes sense btw, I'm just unsure about how `protect` is exactly defined in terms of semantics. I can't find anything on the spec, still going through the book to see if I can find anything.

**Comment by rkoeninger** [comment]
@tizoc We could add another case to `shen.kl-to-lisp` in `backend.lsp` which identifies a symbol with the `"lisp."` prefix, strips it and uppercases the remaining symbol. That's all the macro is trying to do.

That would allow us to drop `platform.shen`, which would also simplify the build process.

I tried converting the macro to straight lisp on an abandoned branch at some point: https://github.com/Shen-Language/shen-cl/blob/ecl-enhancements/src/platform.lisp . That could be the basis for the new case in `shen.kl-to-lisp`.

**Comment by tizoc** [comment]
Ok, found something on page 28 of the third edition of the book. Everything it says is in relation to the rules in a `define`, and in terms of symbols. Outside of `define` rules, how `protect` should behave is undefined, which makes me prefer to leave it as is.

> @tizoc We could add another case to shen.kl-to-lisp in backend.lsp which identifies a symbol with the "lisp." prefix, strips it and uppercases the remaining symbol. That's all the macro is trying to do.

Yes, thats exactly what I had in mind (it is also very similar to how I solved it in Shen/Scheme).

**Comment by tizoc** [comment]
I can give it a try later unless you have already done so.
