### ISSUE TITLE
The Shen CLOS, and the Shen/LISP interface

### ISSUE THREAD

**Issue by bluejay77** [Shen-Language/shen-cl#18]
I have been planning an object oriented capability for Shen.

One way to do this, which seems very good, would be to import the
CLOS, id est the Common LISP Object System, of the underlying LISP to
Shen, exemplaris gratis by using the (lisp.defun...) capability.

But there are problems.

The first one to mention is that this would break the universal
portability of Shen to multiple language environments.

Another problem is that the Shen does not understand the LISP keyword
symbols, beginning with the : character.

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 21
running under Common Lisp, implementation: SBCL
port 2.2 ported by Mark Tarver


(0-) :symbol
:
symbol

(1-)
```

More problems will occur if one tries this one:

[File clos.demo.shen]

```
\\ CLOS Shen AJY 2018-05-20

(defmacro setf-macro
    [setf Form Val] ->
        [lisp.setf Form Val])

(defmacro defclass-macro
    [defclass ClassName Superclasses ListOfSlots]
    ->
    [lisp.defclass ClassName
		   Superclasses
		   ListOfSlots])

(defmacro make-instance-macro
    [make-instance ClassName] ->
        [lisp.make-instance ClassName])

(defmacro defmethod-macro
    [defmethod ClassName ArgumentList MethodCode]
    ->
        [lisp.defmethod
	    ClassName
	    ArgumentList
	    MethodCode])

\*

Demo

Winston-Horn: LISP, 3rd Edition ISBN 0-201-08319-1
Addison-Wesley 1993

Examples pp. 183--205

*\

(defclass article []
  [[title :accessor article-title :initarg nil]
   [author :accessor article-author]])

(defclass computer-article [article])

(defclass business-article [article])

(defclass political-article [article])
```

This will happen:

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 21
running under Common Lisp, implementation: SBCL
port 2.2 ported by Mark Tarver


(0-) (load "clos.demo.shen")
setf-macro
defclass-macro
make-instance-macro
defmethod-macro
The function COMMON-LISP-USER::defclass is undefined.

(1-)
```

The (lisp.defclass...) function will look for the (defclass...)
function from the COMMON-LISP-USER package, whereas the defclass is
in the #<PACKAGE "COMMON-LISP"> package.

The main point of this entry is actually not the Shen CLOS, but the
usability of the Shen/LISP interface (lisp.defclass...) style.

yours, AJY
Finland, the EU

**Comment by tizoc** [comment]
The new `lisp.` form added in #19 should help you with this (it is not ideal for this use case but it at least opens some possibilities that were not available before).

Remember that the Common Lisp namespace is all UPPERCASE.
