### ISSUE TITLE
Get repo set up on Travis-CI

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-cl#2]
@tizoc When you have a minute, could you get this repo set up on Travis-CI?

There's an included .travis.yml file which I imagine will work, but if not, I can get it building. I just can't configure anything on travis.

**Comment by tizoc** [comment]
I enabled this repo on travis, but it doesn't seem to be working.

Also, when pasting the contents of .travis.yml in the validator I get:

- value for addons section is empty, dropping
- in addons section: unexpected key apt, dropping

**Comment by tizoc** [comment]
Ah wait, I think a commit is required to trigger a build.

**Comment by rkoeninger** [comment]
Incidentally, I just pushed a couple of commits.

Looks like the build fails when trying to download the clozure package.

I'll work on it.

Thanks for getting this set up.

**Comment by rkoeninger** [comment]
`sudo` had to be enabled and SBCL has to be installed by downloading a separate package from debian.org as the package on apt has an out of date version.

Build passes.
