### ISSUE TITLE
Can't compare empty absvectors

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-cl#23]
The `CF-VECTORS` function should check if both vectors are empty and immediately return true if so.

https://github.com/Shen-Language/shen-cl/blob/3439aff84c8419ad5b28579ea6443f29c63c9806/src/primitives.lsp#L160-L163

**Comment by tizoc** [comment]
Didn't test it, but I think this version should work without adding much overhead.

```lisp

(DEFUN CF-VECTORS (X Y LX LY)
  (AND
    (= LX LY)
    (OR (ZERO? LX)
        (CF-VECTORS-HELP X Y 0 (1- LX)))))
```

**Comment by tizoc** [comment]
Well, probably not `ZERO?`, thats a Scheme thing, but whatever Common Lisp has.

**Comment by rkoeninger** [comment]
It's `ZEROP`.

Fixed in this commit: https://github.com/Shen-Language/shen-cl/commit/96004d10f3b3ed09f7ed8f892c8d61f91aacbf6e

Tests pass. Tried it out and it no problems.
