### ISSUE TITLE
Pattern matching factorization optimization

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-cl#36]
Will make a version for Shen/CL after I'm done cleaning up the Shen/Scheme version. Will probably have to wait until after #35 to get integrated.

**Comment by rkoeninger** [comment]
(asked a question here but moved it to https://github.com/Shen-Language/shen-sources/issues/82#issuecomment-531584150)

**Comment by tizoc** [comment]
Ok, with #39 merged this one should be much easier now. Not sure if it is better to do it before or after releasing the current changes.

**Comment by tizoc** [comment]
Solved by #41
